services:
  backend:
    environment:
      SPRING_PROFILES_ACTIVE: prod
      CORS_POLICY_ALLOWED_ORIGINS: ${CORS_POLICY_ALLOWED_ORIGINS}
      PRINTSRV_HOST_0: ${PRINTSRV_HOST_0}
      PRINTSRV_PORT_0: ${PRINTSRV_PORT_0}
      PRINTSRV_HOST_1: ${PRINTSRV_HOST_1}
      PRINTSRV_PORT_1: ${PRINTSRV_PORT_1}
      PRINTSRV_HOST_2: ${PRINTSRV_HOST_2}
      PRINTSRV_PORT_2: ${PRINTSRV_PORT_2}
      PRINTSRV_HOST_3: ${PRINTSRV_HOST_3}
      PRINTSRV_PORT_3: ${PRINTSRV_PORT_3}
      PRINTSRV_HOST_4: ${PRINTSRV_HOST_4}
      PRINTSRV_PORT_4: ${PRINTSRV_PORT_4}
      PRINTSRV_HOST_5: ${PRINTSRV_HOST_5}
      PRINTSRV_PORT_5: ${PRINTSRV_PORT_5}
      PRINTSRV_HOST_6: ${PRINTSRV_HOST_6}
      PRINTSRV_PORT_6: ${PRINTSRV_PORT_6}
      PRINTSRV_HOST_7: ${PRINTSRV_HOST_7}
      PRINTSRV_PORT_7: ${PRINTSRV_PORT_7}
      PRINTSRV_HOST_8: ${PRINTSRV_HOST_8}
      PRINTSRV_PORT_8: ${PRINTSRV_PORT_8}
      PRINTSRV_HOST_9: ${PRINTSRV_HOST_9}
      PRINTSRV_PORT_9: ${PRINTSRV_PORT_9}
      PRINTSRV_HOST_10: ${PRINTSRV_HOST_10}
      PRINTSRV_PORT_10: ${PRINTSRV_PORT_10}
      PRINTSRV_HOST_11: ${PRINTSRV_HOST_11}
      PRINTSRV_PORT_11: ${PRINTSRV_PORT_11}
      PRINTSRV_HOST_12: ${PRINTSRV_HOST_12}
      PRINTSRV_PORT_12: ${PRINTSRV_PORT_12}
      PRINTSRV_HOST_13: ${PRINTSRV_HOST_13}
      PRINTSRV_PORT_13: ${PRINTSRV_PORT_13}
    ports:
      - "${BACKEND_PORT:-18080}:8080"

  frontend:
    ports:
      - "${FRONTEND_PORT:-5500}:8080"
