services:
  backend:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      CORS_POLICY_ALLOWED_ORIGINS: ${CORS_POLICY_ALLOWED_ORIGINS}
      PRINTSRV_TREPKO1_HOST: ${PRINTSRV_TREPKO1_HOST:-127.0.0.1}
      PRINTSRV_TREPKO1_PORT: ${PRINTSRV_TREPKO1_PORT:-5561}
      PRINTSRV_TREPKO2_HOST: ${PRINTSRV_TREPKO2_HOST:-127.0.0.1}
      PRINTSRV_TREPKO2_PORT: ${PRINTSRV_TREPKO2_PORT:-5562}
      PRINTSRV_HASSIA1_HOST: ${PRINTSRV_HASSIA1_HOST:-127.0.0.1}
      PRINTSRV_HASSIA1_PORT: ${PRINTSRV_HASSIA1_PORT:-5563}
      PRINTSRV_HASSIA2_HOST: ${PRINTSRV_HASSIA2_HOST:-127.0.0.1}
      PRINTSRV_HASSIA2_PORT: ${PRINTSRV_HASSIA2_PORT:-5564}
      PRINTSRV_HASSIA4_HOST: ${PRINTSRV_HASSIA4_HOST:-127.0.0.1}
      PRINTSRV_HASSIA4_PORT: ${PRINTSRV_HASSIA4_PORT:-5565}
      PRINTSRV_HASSIA5_HOST: ${PRINTSRV_HASSIA5_HOST:-127.0.0.1}
      PRINTSRV_HASSIA5_PORT: ${PRINTSRV_HASSIA5_PORT:-5566}
      PRINTSRV_HASSIA6_HOST: ${PRINTSRV_HASSIA6_HOST:-127.0.0.1}
      PRINTSRV_HASSIA6_PORT: ${PRINTSRV_HASSIA6_PORT:-5567}
      PRINTSRV_GRUNWALD1_HOST: ${PRINTSRV_GRUNWALD1_HOST:-127.0.0.1}
      PRINTSRV_GRUNWALD1_PORT: ${PRINTSRV_GRUNWALD1_PORT:-5571}
      PRINTSRV_GRUNWALD2_HOST: ${PRINTSRV_GRUNWALD2_HOST:-127.0.0.1}
      PRINTSRV_GRUNWALD2_PORT: ${PRINTSRV_GRUNWALD2_PORT:-5572}
      PRINTSRV_HASSIA3_HOST: ${PRINTSRV_HASSIA3_HOST:-127.0.0.1}
      PRINTSRV_HASSIA3_PORT: ${PRINTSRV_HASSIA3_PORT:-5573}
      PRINTSRV_BOSCH_HOST: ${PRINTSRV_BOSCH_HOST:-127.0.0.1}
      PRINTSRV_BOSCH_PORT: ${PRINTSRV_BOSCH_PORT:-5574}
      PRINTSRV_GRUNWALD5_HOST: ${PRINTSRV_GRUNWALD5_HOST:-127.0.0.1}
      PRINTSRV_GRUNWALD5_PORT: ${PRINTSRV_GRUNWALD5_PORT:-5575}
      PRINTSRV_GRUNWALD8_HOST: ${PRINTSRV_GRUNWALD8_HOST:-127.0.0.1}
      PRINTSRV_GRUNWALD8_PORT: ${PRINTSRV_GRUNWALD8_PORT:-5576}
      PRINTSRV_GRUNWALD11_HOST: ${PRINTSRV_GRUNWALD11_HOST:-127.0.0.1}
      PRINTSRV_GRUNWALD11_PORT: ${PRINTSRV_GRUNWALD11_PORT:-5577}
    ports:
      - "${BACKEND_PORT:?BACKEND_PORT is required in prod env}:8080"

  frontend:
    ports:
      - "${FRONTEND_PORT:?FRONTEND_PORT is required in prod env}:8080"
