services:
  postgres:
    image: postgres:17-alpine
    container_name: scada-mobile-postgres
    environment:
      POSTGRES_DB: ${SCADA_MOBILE_POSTGRES_DB:-scada_mobile}
      POSTGRES_USER: ${SCADA_MOBILE_POSTGRES_USER:-scada_user}
      POSTGRES_PASSWORD: ${SCADA_MOBILE_DATABASE_PASSWORD:?SCADA_MOBILE_DATABASE_PASSWORD is required in prod env}
    volumes:
      - scada-mobile-postgres-data:/var/lib/postgresql/data
    ports:
      - "${SCADA_MOBILE_POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  backend:
    image: scada-mobile/backend:0.1.0
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        USER_ID: ${HOST_UID}
        GROUP_ID: ${HOST_GID}
    restart: no
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./backend/logs:/app/logs
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SCADA_MOBILE_CORS_POLICY_ALLOWED_ORIGINS: ${SCADA_MOBILE_CORS_POLICY_ALLOWED_ORIGINS}
      SCADA_MOBILE_DATABASE_URL: ${SCADA_MOBILE_DATABASE_URL:-jdbc:postgresql://${SCADA_MOBILE_POSTGRES_HOST:-postgres}:5432/${SCADA_MOBILE_POSTGRES_DB:-scada_mobile}}
      SCADA_MOBILE_DATABASE_USERNAME: ${SCADA_MOBILE_DATABASE_USERNAME:-scada_user}
      SCADA_MOBILE_DATABASE_PASSWORD: ${SCADA_MOBILE_DATABASE_PASSWORD:?SCADA_MOBILE_DATABASE_PASSWORD is required in prod env}
      SCADA_MOBILE_ADMIN_BOOTSTRAP_CODE: ${SCADA_MOBILE_ADMIN_BOOTSTRAP_CODE}
      SCADA_MOBILE_ADMIN_BOOTSTRAP_PASSWORD: ${SCADA_MOBILE_ADMIN_BOOTSTRAP_PASSWORD}
      SCADA_MOBILE_JWT_ACCESS_SECRET: ${SCADA_MOBILE_JWT_ACCESS_SECRET:?SCADA_MOBILE_JWT_ACCESS_SECRET is required in prod env}
      SCADA_MOBILE_JWT_REFRESH_SECRET: ${SCADA_MOBILE_JWT_REFRESH_SECRET:?SCADA_MOBILE_JWT_REFRESH_SECRET is required in prod env}
      SCADA_MOBILE_PRINTSRV_TREPKO1_HOST: ${SCADA_MOBILE_PRINTSRV_TREPKO1_HOST:-999.9.9.9}
      SCADA_MOBILE_PRINTSRV_TREPKO1_PORT: ${SCADA_MOBILE_PRINTSRV_TREPKO1_PORT:-9999}
      SCADA_MOBILE_PRINTSRV_TREPKO2_HOST: ${SCADA_MOBILE_PRINTSRV_TREPKO2_HOST:-999.9.9.9}
      SCADA_MOBILE_PRINTSRV_TREPKO2_PORT: ${SCADA_MOBILE_PRINTSRV_TREPKO2_PORT:-9999}
      SCADA_MOBILE_PRINTSRV_HASSIA1_HOST: ${SCADA_MOBILE_PRINTSRV_HASSIA1_HOST:-999.9.9.9}
      SCADA_MOBILE_PRINTSRV_HASSIA1_PORT: ${SCADA_MOBILE_PRINTSRV_HASSIA1_PORT:-9999}
      SCADA_MOBILE_PRINTSRV_HASSIA2_HOST: ${SCADA_MOBILE_PRINTSRV_HASSIA2_HOST:-999.9.9.9}
      SCADA_MOBILE_PRINTSRV_HASSIA2_PORT: ${SCADA_MOBILE_PRINTSRV_HASSIA2_PORT:-9999}
      SCADA_MOBILE_PRINTSRV_HASSIA4_HOST: ${SCADA_MOBILE_PRINTSRV_HASSIA4_HOST:-999.9.9.9}
      SCADA_MOBILE_PRINTSRV_HASSIA4_PORT: ${SCADA_MOBILE_PRINTSRV_HASSIA4_PORT:-9999}
      SCADA_MOBILE_PRINTSRV_HASSIA5_HOST: ${SCADA_MOBILE_PRINTSRV_HASSIA5_HOST:-999.9.9.9}
      SCADA_MOBILE_PRINTSRV_HASSIA5_PORT: ${SCADA_MOBILE_PRINTSRV_HASSIA5_PORT:-9999}
      SCADA_MOBILE_PRINTSRV_HASSIA6_HOST: ${SCADA_MOBILE_PRINTSRV_HASSIA6_HOST:-999.9.9.9}
      SCADA_MOBILE_PRINTSRV_HASSIA6_PORT: ${SCADA_MOBILE_PRINTSRV_HASSIA6_PORT:-9999}
      SCADA_MOBILE_PRINTSRV_GRUNWALD1_HOST: ${SCADA_MOBILE_PRINTSRV_GRUNWALD1_HOST:-999.9.9.9}
      SCADA_MOBILE_PRINTSRV_GRUNWALD1_PORT: ${SCADA_MOBILE_PRINTSRV_GRUNWALD1_PORT:-9999}
      SCADA_MOBILE_PRINTSRV_GRUNWALD2_HOST: ${SCADA_MOBILE_PRINTSRV_GRUNWALD2_HOST:-999.9.9.9}
      SCADA_MOBILE_PRINTSRV_GRUNWALD2_PORT: ${SCADA_MOBILE_PRINTSRV_GRUNWALD2_PORT:-9999}
      SCADA_MOBILE_PRINTSRV_HASSIA3_HOST: ${SCADA_MOBILE_PRINTSRV_HASSIA3_HOST:-999.9.9.9}
      SCADA_MOBILE_PRINTSRV_HASSIA3_PORT: ${SCADA_MOBILE_PRINTSRV_HASSIA3_PORT:-9999}
      SCADA_MOBILE_PRINTSRV_BOSCH_HOST: ${SCADA_MOBILE_PRINTSRV_BOSCH_HOST:-999.9.9.9}
      SCADA_MOBILE_PRINTSRV_BOSCH_PORT: ${SCADA_MOBILE_PRINTSRV_BOSCH_PORT:-9999}
      SCADA_MOBILE_PRINTSRV_GRUNWALD5_HOST: ${SCADA_MOBILE_PRINTSRV_GRUNWALD5_HOST:-999.9.9.9}
      SCADA_MOBILE_PRINTSRV_GRUNWALD5_PORT: ${SCADA_MOBILE_PRINTSRV_GRUNWALD5_PORT:-9999}
      SCADA_MOBILE_PRINTSRV_GRUNWALD8_HOST: ${SCADA_MOBILE_PRINTSRV_GRUNWALD8_HOST:-999.9.9.9}
      SCADA_MOBILE_PRINTSRV_GRUNWALD8_PORT: ${SCADA_MOBILE_PRINTSRV_GRUNWALD8_PORT:-9999}
      SCADA_MOBILE_PRINTSRV_GRUNWALD11_HOST: ${SCADA_MOBILE_PRINTSRV_GRUNWALD11_HOST:-999.9.9.9}
      SCADA_MOBILE_PRINTSRV_GRUNWALD11_PORT: ${SCADA_MOBILE_PRINTSRV_GRUNWALD11_PORT:-9999}
    ports:
      - "${SCADA_MOBILE_BACKEND_PORT:?SCADA_MOBILE_BACKEND_PORT is required in prod env}:8080"
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    image: scada-mobile/frontend:0.1.0
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "${SCADA_MOBILE_FRONTEND_PORT:?SCADA_MOBILE_FRONTEND_PORT is required in prod env}:8080"
    depends_on:
      - backend

volumes:
  scada-mobile-postgres-data:
