-- Перманентное состояние «последняя партия» и реестр токенов автоматов (СКАДА).
--
-- production_notifications — единственный источник истины о состоянии «последняя партия»
-- по каждому аппарату: одна строка на аппарат, обновляется на месте при toggle
-- (установка / снятие). Читается фронтендом (через WS/REST) и СКАДА-системами.
CREATE TABLE production_notifications
(
    notification_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    unit_id         BIGINT                                  NOT NULL,
    creator_type    VARCHAR(16)                             NOT NULL,
    creator_id      VARCHAR(255)                            NOT NULL,
    is_active       BOOLEAN                                 NOT NULL,
    activated_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    deactivated_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_production_notifications PRIMARY KEY (notification_id)
);

ALTER TABLE production_notifications
    ADD CONSTRAINT uc_production_notifications_unit UNIQUE (unit_id);

ALTER TABLE production_notifications
    ADD CONSTRAINT FK_PRODUCTION_NOTIFICATIONS_ON_UNIT FOREIGN KEY (unit_id) REFERENCES units (unit_id);

CREATE INDEX idx_production_notifications_is_active ON production_notifications (is_active);

-- machine_tokens — реестр выданных machine-JWT для автоматов (СКАДА).
-- Хранение jti позволяет отозвать конкретный токен до истечения его срока.
-- Сам токен не хранится — только его идентификатор и метаданные.
CREATE TABLE machine_tokens
(
    token_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    unit_id    BIGINT                                  NOT NULL,
    jti        VARCHAR(64)                             NOT NULL,
    issued_by  BIGINT,
    issued_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    expires_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    revoked_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_machine_tokens PRIMARY KEY (token_id)
);

ALTER TABLE machine_tokens
    ADD CONSTRAINT uc_machine_tokens_jti UNIQUE (jti);

ALTER TABLE machine_tokens
    ADD CONSTRAINT FK_MACHINE_TOKENS_ON_UNIT FOREIGN KEY (unit_id) REFERENCES units (unit_id);

ALTER TABLE machine_tokens
    ADD CONSTRAINT FK_MACHINE_TOKENS_ON_ISSUED_BY FOREIGN KEY (issued_by) REFERENCES users (user_id);
