CREATE TABLE device_types
(
    type_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code    VARCHAR(255)                            NOT NULL,
    name    VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_device_types PRIMARY KEY (type_id)
);

CREATE TABLE roles
(
    role_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_roles PRIMARY KEY (role_id)
);

CREATE TABLE unit_devices
(
    device_id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    unit_id      BIGINT                                  NOT NULL,
    type_id      BIGINT                                  NOT NULL,
    code         VARCHAR(255)                            NOT NULL,
    display_name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_unit_devices PRIMARY KEY (device_id)
);

CREATE TABLE units
(
    unit_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    workshop_id BIGINT                                  NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    is_active   BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_units PRIMARY KEY (unit_id)
);

CREATE TABLE user_unit_assignments
(
    assignment_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id       BIGINT                                  NOT NULL,
    unit_id       BIGINT                                  NOT NULL,
    assigned_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    is_active     BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_user_unit_assignments PRIMARY KEY (assignment_id)
);

CREATE TABLE users
(
    user_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    role_id   BIGINT                                  NOT NULL,
    full_name VARCHAR(255)                            NOT NULL,
    is_active BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (user_id)
);

CREATE TABLE workshops
(
    workshop_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    is_active   BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_workshops PRIMARY KEY (workshop_id)
);

ALTER TABLE device_types
    ADD CONSTRAINT uc_device_types_code UNIQUE (code);

ALTER TABLE units
    ADD CONSTRAINT FK_UNITS_ON_WORKSHOP FOREIGN KEY (workshop_id) REFERENCES workshops (workshop_id);

ALTER TABLE unit_devices
    ADD CONSTRAINT FK_UNIT_DEVICES_ON_TYPE FOREIGN KEY (type_id) REFERENCES device_types (type_id);

ALTER TABLE unit_devices
    ADD CONSTRAINT FK_UNIT_DEVICES_ON_UNIT FOREIGN KEY (unit_id) REFERENCES units (unit_id);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_ROLE FOREIGN KEY (role_id) REFERENCES roles (role_id);

ALTER TABLE user_unit_assignments
    ADD CONSTRAINT FK_USER_UNIT_ASSIGNMENTS_ON_UNIT FOREIGN KEY (unit_id) REFERENCES units (unit_id);

ALTER TABLE user_unit_assignments
    ADD CONSTRAINT FK_USER_UNIT_ASSIGNMENTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (user_id);
