ALTER TABLE units
    ADD COLUMN printsrv_instance_id VARCHAR(255);

ALTER TABLE units
    ADD CONSTRAINT uc_units_printsrv_instance_id UNIQUE (printsrv_instance_id);

CREATE INDEX idx_units_printsrv_instance_id ON units (printsrv_instance_id);

CREATE TABLE user_notification_settings
(
    setting_id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id                  BIGINT                                  NOT NULL,
    unit_id                  BIGINT                                  NOT NULL,
    system_sound_enabled     BOOLEAN                                 NOT NULL,
    system_vibration_enabled BOOLEAN                                 NOT NULL,
    android_push_enabled     BOOLEAN                                 NOT NULL,
    is_active                BOOLEAN                                 NOT NULL,
    updated_at               TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_user_notification_settings PRIMARY KEY (setting_id),
    CONSTRAINT uc_user_notification_settings_user_unit UNIQUE (user_id, unit_id)
);

ALTER TABLE user_notification_settings
    ADD CONSTRAINT fk_user_notification_settings_on_user
        FOREIGN KEY (user_id) REFERENCES users (user_id);

ALTER TABLE user_notification_settings
    ADD CONSTRAINT fk_user_notification_settings_on_unit
        FOREIGN KEY (unit_id) REFERENCES units (unit_id);

CREATE INDEX idx_user_notification_settings_user_id ON user_notification_settings (user_id);
CREATE INDEX idx_user_notification_settings_unit_id ON user_notification_settings (unit_id);
