CREATE TABLE IF NOT EXISTS push_subscriptions (
    installation_id VARCHAR(50) PRIMARY KEY,
    endpoint VARCHAR(1024) NOT NULL,
    p256dh_key VARCHAR(255) NOT NULL,
    auth_key VARCHAR(255) NOT NULL,
    platform VARCHAR(50) NOT NULL,
    app_channel VARCHAR(50) NOT NULL,
    preferred_workshop_id VARCHAR(100),
    preferred_unit_id VARCHAR(100),
    registered_at TIMESTAMP WITH TIME ZONE NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS notification_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    installation_id VARCHAR(50) NOT NULL,
    payload CLOB NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    retry_count INTEGER NOT NULL DEFAULT 0,
    next_retry_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    processed_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX IF NOT EXISTS idx_push_subscriptions_active ON push_subscriptions (active);
CREATE INDEX IF NOT EXISTS idx_notification_outbox_status_retry_created
    ON notification_outbox (status, next_retry_at, created_at);
CREATE INDEX IF NOT EXISTS idx_notification_outbox_installation
    ON notification_outbox (installation_id);
