CREATE TABLE device_catalog
(
    catalog_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type_id      BIGINT                                  NOT NULL,
    code         VARCHAR(255)                            NOT NULL,
    display_name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_device_catalog PRIMARY KEY (catalog_id),
    CONSTRAINT fk_device_catalog_on_type FOREIGN KEY (type_id) REFERENCES device_types (type_id)
);

-- Перенести уникальные комбинации (type_id, code, display_name) в справочник
INSERT INTO device_catalog (type_id, code, display_name)
SELECT DISTINCT type_id, code, display_name
FROM unit_devices;

-- Создать временную таблицу для маппинга
CREATE TABLE tmp_unit_devices_migration AS
SELECT
    ud.device_id AS old_device_id,
    ud.unit_id,
    dc.catalog_id
FROM unit_devices ud
         JOIN device_catalog dc ON dc.type_id = ud.type_id
    AND dc.code = ud.code
    AND dc.display_name = ud.display_name;

-- Удалить старую таблицу unit_devices
DROP TABLE unit_devices;

-- Создать новую таблицу unit_devices (связь unit ↔ catalog)
CREATE TABLE unit_devices
(
    device_id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    unit_id    BIGINT                                  NOT NULL,
    catalog_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_unit_devices PRIMARY KEY (device_id),
    CONSTRAINT fk_unit_devices_on_unit FOREIGN KEY (unit_id) REFERENCES units (unit_id),
    CONSTRAINT fk_unit_devices_on_catalog FOREIGN KEY (catalog_id) REFERENCES device_catalog (catalog_id)
);

-- Вставить данные из временной таблицы
INSERT INTO unit_devices (unit_id, catalog_id)
SELECT unit_id, catalog_id
FROM tmp_unit_devices_migration;

-- Удалить временную таблицу
DROP TABLE tmp_unit_devices_migration;
