-- V8__create_admin_notifications.sql
-- Таблица для системных уведомлений администратору (авто-обнаружение устройств, расхождения и т.п.)

CREATE TABLE admin_notifications
(
    notification_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type            VARCHAR(50)  NOT NULL,
    severity        VARCHAR(20)  NOT NULL,
    instance_id     VARCHAR(255) NOT NULL,
    device_code     VARCHAR(255),
    message         TEXT         NOT NULL,
    is_read         BOOLEAN      NOT NULL DEFAULT false,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_admin_notifications PRIMARY KEY (notification_id)
);

CREATE INDEX idx_admin_notifications_unread ON admin_notifications (is_read, created_at DESC);
CREATE INDEX idx_admin_notifications_instance ON admin_notifications (instance_id, created_at DESC);
